### PR TITLE
fetching events using versioning

### PR DESCRIPTION
**Pull request by chandan5**
@nisargjhaveri please review

### CODE REVIEW

**Comment by chandan5** [comment]
@nisargjhaveri UI and Notifications are left. Rest seems done. Kindly review. I will add notifications part soon. @hharchani Can you handle UI for popup?

**Comment by hharchani** [comment]
Sure @chandan5 
Can you tell me how do I install it?

**Comment by chandan5** [comment]
Installation instructions can be seen in readme over here -> https://github.com/chandan5/Facebook-Notifications. 
For console (popup.html) you can right click the extension logo on right side of search bar and select last option that says "Inspect Popup".
For console(background.html) you can click on background.html on chrome://extension page for felicity16 extension.

**Comment by nisargjhaveri** [comment]
@chandan5, I briefly looked at the code. Can't see any major problem. (Have some minor issues in mind, but meh, later) You're free to merge and continue. :)

**Pull request merged**
